### ISSUE TITLE
DarkSigns rewritten

### ISSUE THREAD

**Issue by hax-simulator** [xmakina/darksigns.com#2]
Hello xmakina,

I recently found that you have restored the DarkSigns site, which is a great thing. 

I tried to contact you before but did not manage get through. A couple of years back, i created the Hax Simulator framework, a basis for creating hacking games quite similar to DarkSigns. As a proof of concept, i migrated the main DarkSigns campaign from sources and walkthroughs to the Hax framework. 

You can check out my project here:
[https://hax-simulator.blogspot.com](https://hax-simulator.blogspot.com) 
Maybe you could add a reference to my project to the DarkSigns site, i would really appreciate that.

Also, i wanted to ask you whether you dont have the sources or some walkthroughs for the Matrix and ISA missions. I intended to migrate those to Hax as well, but i found no resources on them anywhere on the net.

I was also thinking about the continuation of the main mission. There were some hints in the source code, but not much. Do you by any chance know anything about how the storyline was to be continued?

Thanks and looking forward to hearing from you!
mio (creator of Hax Simulator)

**Comment by xmakina** [comment]
hey @hax-simulator, I've only just spotted this.

I'd rather keep the website as it was rather than altering it to link to other projects. It's archival, not promotional.

I've not got any source code or original files; DarkSigns was several decades and computers ago, sorry.

Best of luck for your future projects!
